# Generated by Django 4.2.7 on 2024-05-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_flutter', '0002_message_delete_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='gpt_response',
            field=models.TextField(blank=True),
        ),
    ]
